# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrosApp', '0002_remove_videos_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='name',
            field=models.TextField(default='a'),
        ),
    ]
