# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrosApp', '0003_videos_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='path',
            field=models.TextField(default='.'),
        ),
    ]
